name: 'project2'
version: '1.0.0'
config-version: 2

profile: 'project2'

model-paths: ['models']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']
analysis-paths: ['analyses']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  project2:
    +materialized: table

    silver:
      +materialized: table
      +tags: ['silver']

    gold:
      +materialized: view
      +tags: ['gold']

seeds:
  project2:

snapshots:
  project2:
    +target_schema: youtube_analytics
