name: 'project2'
version: '1.0.0'
config-version: 2

profile: 'project2'

seed-paths: ['seeds']
snapshot-paths: ['snapshots']

model-paths: ['models']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  project2:
    +materialized: table

    silver:
      +schema: staging_youtube
      +tags: ['silver']

    gold:
      +schema: analytics_youtube
      +materialized: table
      +tags: ['gold']

seeds:
  project2:
    +schema: analytics_youtube

snapshots:
  project2:
    +target_schema: analytics_youtube