name: 'project2'
version: '1.0.0'
config-version: 2

profile: 'project2'

model-paths: ['models']
seed-paths: ['seeds']
snapshot-paths: ['snapshots']
analysis-paths: ['analyses']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  project2:
    +materialized: table

    silver:
      +tags: ['silver']
      +database: youtube_dbt
    gold:
      +tags: ['gold']
      +database: youtube_dbt

    analytics:
      +tags: ['analytics']
      +materialized: view
      +database: youtube_dbt

    analytics_secure:
      +tags: ['secure']
      +materialized: view
      +database: youtube_dbt
seeds:
  project2:
    +database: youtube_gold

snapshots:
  project2:
    +target_schema: youtube_gold
